apiVersion: apps/v1
kind: Deployment
metadata:
  name: rexzheng
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: testforacr
      containers:
        - name: flaskapp-demo
          image: REPOSITORY:ID
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: rexzheng
  namespace: test
  labels:
    app: web
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: web
  type: ClusterIP

