name: CI
on:
  push:
    branches: [ main ]

jobs:
  CIJOB:
    runs-on: AWS-EC2-smartcmp
    env:
      REGION: "ap-northeast-1"
      EKSCLUSTER: "test-eks"
      ECR: "555411786219.dkr.ecr.ap-northeast-1.amazonaws.com"
      DOCKERIMAGE: "rexzhengflask"
      K8SYAML: "UnderArmourtest.yaml"
      SHFILE: "apply.sh"

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: build
      run: |
        docker build -t $ECR/$DOCKERIMAGE:$GITHUB_RUN_ID .
        aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR
        docker push $ECR/$DOCKERIMAGE:$GITHUB_RUN_ID
        docker image ls | grep $ECR/$DOCKERIMAGE
        docker rmi $ECR/$DOCKERIMAGE:$GITHUB_RUN_ID
    - name: deploy
      run: |
        aws eks --region $REGION update-kubeconfig --name $EKSCLUSTER
        eval sed -i 's!REPOSITORY!$ECR!g' $K8SYAML
        eval sed -i 's!IMAGE!$DOCKERIMAGE!g' $K8SYAML
        eval sed -i 's!ID!$GITHUB_RUN_ID!g' $K8SYAML
        sh $SHFILE

